steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-devops-pipeline/my-repo-devops-pipeline/my-flask-app', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-devops-pipeline/my-repo-devops-pipeline/my-flask-app']

images:
  - 'us-central1-docker.pkg.dev/project-devops-pipeline/my-repo-devops-pipeline/my-flask-app'

